name: CI

on:
  push:

jobs:
  code_quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

  check_unused_files:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          tool_versions: |
            shellcheck 0.9.0
          run: shellcheck scripts/*.sh
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run knip
        run: pnpm run knip

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
        tool_versions: |
          shellcheck 0.9.0
        run: shellcheck scripts/*.sh
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Install dependencies
      run: pnpm install
    # - name: Build
    #   run: pnpm build
